supa_key="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ibGhkd2p3aXp4Z3JiZ3hrbXl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NDA3MTIsImV4cCI6MjA1NDQxNjcxMn0.q8waxRsiLXyccmEEa_u_ltqKP1tBXpL9OrpnfzvOMeQ"
supa_url="https://mblhdwjwizxgrbgxkmyx.supabase.co"
courier_auth_token="NTcxYjVjNjEtNzIzOS00OTRkLTlkYzQtOWIwOGI1ODJjNWFh"
